<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net10.0-windows8.0</TargetFramework>
    <Nullable>enable</Nullable>
    <UseWindowsForms>true</UseWindowsForms>
    <ImplicitUsings>enable</ImplicitUsings>
    <ApplicationIcon>juxtapose.ico</ApplicationIcon>
    <SupportedOSPlatformVersion>8.0</SupportedOSPlatformVersion>
  </PropertyGroup>

  <ItemGroup>
    <Content Include="juxtapose.ico" />
  </ItemGroup>

  <ItemGroup>
    <None Include="wwwroot\**\*">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.Office.Interop.Excel" Version="15.0.4795.1001" />
    <PackageReference Include="Microsoft.Web.WebView2" Version="1.0.2903.40" />
    <PackageReference Include="SharpSvn" Version="1.14003.290" />
  </ItemGroup>

</Project>